### ISSUE TITLE
 Minicart generates unwanted click

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/minicart#172]
The Minicart block is being clickable integer. The add more product or product removal button is generating undesirable clicks and leading to the product page.

## Expected Behavior
Expected behavior would be to click on the image and product name only and not on the entire container.

![Captura de Tela 2019-08-09 às 10 09 08](https://user-images.githubusercontent.com/44183746/62781349-29262980-ba8e-11e9-888e-11732bedd5c6.png)

**Comment by klzns** [comment]
Thanks for the bug report!

Next time we recommend that you open issues at the repo:
https://github.com/vtex-apps/store-discussion/

We are centralizing all community feature or bug report there.

**Comment by klzns** [comment]
Fixed
