### ISSUE TITLE
Wrong minicart scroll

### ISSUE THREAD

**Issue by ricardomatta** [vtex-apps/minicart#173]
**Is your feature request related to a problem? Please describe.**
As shown in the following video, there is a wrong scroll in minicart.
https://youtu.be/AyB5WqOhwMA
The expected behavior would be to block scrolling on the div behind minicart.

**Comment by victorhmp** [comment]
Hi @ricardomatta !
Thanks for opening this issue! And we're glad to inform that this is fixed in the new and *flexible* `minicart.v2` :)

In the future, please open this kind of issues at [Store Discussion](https://github.com/vtex-apps/store-discussion)
