### ISSUE TITLE
Allow translate minicart texts via site editor

### ISSUE THREAD

**Issue by miguel-rosa** [vtex-apps/minicart#256]
**Is your feature request related to a problem? Please describe.**
Some terms of minicart popup and of drawer are automatic translated, and we need autonomy to change, because at some countries, the terms could be improved

**Describe the solution you'd like**
We need to be able to insert text of "Subtotal", "Discounts", "Totatl" and "Go to checkout" of popup and of drawer via site editor. 

**Additional context**
Terms that we need to be able to edit
![image](https://user-images.githubusercontent.com/60516089/97173683-b75bfd80-176f-11eb-9a53-ae63a5a578e4.png)
![image](https://user-images.githubusercontent.com/60516089/97173740-ce025480-176f-11eb-806c-0c12719c9624.png)

**Comment by Mecrano** [comment]
Hi @miguel-rosa , you can change this text by graphQL request, here is the documentation: https://vtex.io/docs/recipes/development/overwriting-the-messages-app/

Regards, Edwin.

**Comment by miguel-rosa** [comment]
> Hi @miguel-rosa , you can change this text by graphQL request, here is the documentation: https://vtex.io/docs/recipes/development/overwriting-the-messages-app/
> 
> Regards, Edwin.

Perfect, thanks!
