### ISSUE TITLE
Container não crescendo para comportar mais itens

### ISSUE THREAD

**Issue by jgfidelis** [vtex-apps/minicart#80]
Ver ss: 
<img width="377" alt="screen shot 2019-01-14 at 3 52 21 pm" src="https://user-images.githubusercontent.com/4925068/51130612-86b60880-1814-11e9-8d0f-630cda6acce6.png">

Existem itens renderizados, o stepper e o preço da large, mas não aparecem, scroll dentro do minicart não funciona... 🤔

**Comment by paul0vinicius** [comment]
O problema não foi mais detectado e aparentemente está corrigido. Por isso essa issue está sendo fechada.
