### ISSUE TITLE
Product Summary overlapping with remove icon

### ISSUE THREAD

**Issue by jgfidelis** [vtex-apps/minicart#95]
<img width="335" alt="screen shot 2019-02-07 at 12 15 34 pm" src="https://user-images.githubusercontent.com/4925068/52417156-5dfef700-2ad2-11e9-9e6c-9f2c6dd1900a.png">

**Comment by paul0vinicius** [comment]
Fixed in https://github.com/vtex-apps/product-summary/pull/106.
